#include <stdio.h>

int main()
{
    int branches, products, i, j;
    int shipment[10][10];
    int revenuePerUnit[10];
    int totalRevenue[10] = {0};

    // Input number of branches and products
    printf("Enter number of branches: ");
    scanf("%d", &branches);

    printf("Enter number of products: ");
    scanf("%d", &products);

    // Input shipment data
    printf("\nEnter units shipped by each branch:\n");
    for (i = 0; i < branches; i++)
    {
        printf("Branch %d:\n", i + 1);

        for (j = 0; j < products; j++)
        {
            printf("Product %d units: ", j + 1);
            scanf("%d", &shipment[i][j]);
        }
    }

    // Input revenue per unit for each product
    printf("\nEnter revenue per unit for each product:\n");
    for (j = 0; j < products; j++)
    {
        printf("Product %d revenue: ", j + 1);
        scanf("%d", &revenuePerUnit[j]);
    }

    // Calculate total revenue for each branch
    for (i = 0; i < branches; i++)
    {
        for (j = 0; j < products; j++)
        {
            totalRevenue[i] += shipment[i][j] * revenuePerUnit[j];
        }
    }

    // Display total revenue
    printf("\nTotal Revenue Generated by Each Branch:\n");
    for (i = 0; i < branches; i++)
    {
        printf("Branch %d = %d\n", i + 1, totalRevenue[i]);
    }

    return 0;
}